---

- hosts: all
  remote_user: ec2-user
  become: yes
  any_errors_fatal: true
  gather_facts: no
  vars:
    - service: thorchaind
  roles:
    - stop
    - reset-validators-with-genesis
    - start
