---

- name: Stop service
  service: name=thorchaind state=stopped

- name: Delete files
  file: "path={{item}} state=absent"
  with_items:
  - /usr/bin/thorchaind
  - /home/thorchaind/.thorchaind
  - /home/thorchaind/.thorchaincli
