---

- name: Fetch genesis.json
  fetch: "src=/home/thorchaind/.thorchaind/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: thorchaind

- name: Fetch config.toml
  fetch: "src=/home/thorchaind/.thorchaind/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: thorchaind

