---

- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_propose = '
    line: 'timeout_propose = 1000'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_propose_delta = '
    line: 'timeout_propose_delta = 300'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_prevote = '
    line: 'timeout_prevote = 500'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_prevote_delta = '
    line: 'timeout_prevote_delta = 300'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_precommit = '
    line: 'timeout_precommit = 500'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_precommit_delta = '
    line: 'timeout_precommit_delta = 300'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^timeout_commit = '
    line: 'timeout_commit = 480'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^flush_throttle_timeout = '
    line: 'flush_throttle_timeout = 10'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^max_packet_msg_payload_size = '
    line: 'max_packet_msg_payload_size = 10240'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^grpc_max_open_connections = '
    line: 'grpc_max_open_connections = 10000'
  become: yes
  become_user: thorchaind
- lineinfile:
    path: ~/.thorchaind/config/config.toml
    regexp: '^max_open_connections = '
    line: 'max_open_connections = 10000'
  become: yes
  become_user: thorchaind
- pam_limits:
    domain: thorchaind
    limit_type: '-'
    limit_item: nofile
    value: 12000
- name: Set tcp_tw_reuse
  become: yes
  shell: "echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse"